### ISSUE TITLE
syncToSynapse not returning

### ISSUE THREAD

**Issue by xtYao** [Sage-Bionetworks/synapserutils#16]
## Code/output:
 > library(synapserutils)                                                                            
 Loading required package: synapser                                                                  
                                                                                                     
 TERMS OF USE NOTICE:                                                                                
   When using Synapse, remember that the terms and conditions of use require that you:               
   1) Attribute data contributors when discussing these data or results from these data.             
   2) Not discriminate, identify, or recontact individuals or groups represented by the data.        
   3) Use and contribute only data de-identified to HIPAA standards.                                 
   4) Redistribute data only under these same terms of use.                                          
                                                                                                     
 > synLogin()                                                                                        
 Welcome, Xiaotong Yao!NULL                                                                          
 > syncToSynapse("~/manifest.synapse.txt", dryRun = T)                                               
 Validation and upload of: ~/manifest.synapse.txtValidating columns of manifest.....OKValidating tha\
 t all paths exist..OKValidating that all files are unique...OKValidating provenance...OKValidating \
 that parents exist and are containers...OK==================================================We are \
 about to upload 2 files with a total size of 1.2MB. ===============================================\
 ===NULL                                                                                             
!> syncToSynapse("~/manifest.synapse.txt")   

## SessionInfo
!> sessionInfo()                                                                                     
 R version 3.5.1 (2018-07-02)                                                                        
 Platform: x86_64-apple-darwin15.6.0 (64-bit)                                                        
 Running under: macOS High Sierra 10.13.6                                                            
                                                                                                     
 Matrix products: default                                                                            
 BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib                   
 LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib                 
                                                                                                     
 locale:                                                                                             
 [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8                                   
                                                                                                     
 attached base packages:                                                                             
 [1] stats     graphics  grDevices utils     datasets  methods   base                                
                                                                                                     
 other attached packages:                                                                            
 [1] synapserutils_0.1.5 synapser_0.6.56                                                             
                                                                                                     
 loaded via a namespace (and not attached):                                                          
 [1] compiler_3.5.1        R6_2.3.0              tools_3.5.1                                         
 [4] codetools_0.2-15      pack_0.1-1            PythonEmbedInR_0.3.34

**Comment by brucehoff** [comment]
https://sagebionetworks.jira.com/browse/SWC-4862

**Comment by xtYao** [comment]
Hi Bruce,

Thank you very much, this is very helpful.

I know that NCI or TCGA team is moving the actual storage point away from
tcgaftps.nci.nih.gov to some new GDC location right at this moment. They
gave us a vague timeline and a pair of new credentials, so that as soon as
the data migration is complete I will be asked for the new credentials
rather than the NIHEXT before. Now that when I input this old NIHEXT
credentials onto the web portal or R API while neither responds might
related to the unfinished migration. I will contact NCI again to see if I
can obtain some more detailed answer from them. Meanwhile, could you tell
me if there's any notification I can receive from Synapse that the new
storage location is ready to receive my data through Synapse?

Sincerely appreciate your help,
*Xiaotong Yao*
PhD student, Imielinski lab

Weill Cornell Medicine
xiy2006@med.cornell.edu

**Comment by brucehoff** [comment]
Dear Xiaotong:  I have made an inquiry and will pass along what I hear back.

**Comment by larssono** [comment]
Hi Xiaotong:  What project are you trying to upload to?  Have you tried increasing the debug level to get additional feedback of where syncToSynapse is hanging?

**Comment by brucehoff** [comment]
Larsson:
There seem to be two parallel email threads.  In the other one Xiaotong
says:

"Thank you so much for your help. The TCGA coordinator says she can still
transfer files by Synapse but my credentials were activated after they
started the migration process so even though I used to be able to login to
the SFTP storage point directly, it is likely that to upload through
Synapse is not enabled. At this point, none of us has much to do except
waiting on the migration process to finish. Meanwhile I'll have to ask my
colleagues to do the uploading for me."

Does this help?
Bruce

**Comment by brucehoff** [comment]
Per @xtYao:
```
Thank you so much for your help. The TCGA coordinator says she can still transfer files by Synapse but my credentials were activated after they started the migration process so even though I used to be able to login to the SFTP storage point directly, it is likely that to upload through Synapse is not enabled. At this point, none of us has much to do except waiting on the migration process to finish. Meanwhile I'll have to ask my colleagues to do the uploading for me.
```
